title: Knots, Braids, the Jones Polynomial and Khovanov Homology
description: A master's thesis by Ronald Huidrom
show_downloads: false

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
