title: A treatise of the Jones polynomial
description: A master's thesis in low-dimensional topology (May 2024)
show_downloads: false

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
